Repository XdithyX/TheCocktail, pull requests merged in 2022-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: hacktober-accepted

#2 first aos
  package-lock.json
  package.json
  src/Context.js
  src/components/Cocktail.js
Labels: hacktoberfest-accepted

#3 added stars
  src/App.css
  src/App.js
  src/Context.js
  src/components/Cocktail.js
  src/components/Cocktaillist.js
  src/components/Navbar.js
  src/components/Star/Star.css
  src/components/Star/Star.js
  src/index.css
Labels: hacktober-accepted, hacktoberfest-accepted

#4 anims added
  src/components/Cocktail.js
  src/components/Cocktaillist.js
  src/components/Searchbar.js
  src/index.css
Labels: hacktober-accepted, hacktoberfest-accepted

#6 Updated readme
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted

#7 Update README.md
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted

#8 Update App.js
  src/App.js
Labels: hacktober-accepted, hacktoberfest-accepted

#9 Update Home.js
  src/pages/Home.js
Labels: hacktober-accepted, hacktoberfest-accepted
